# Generated by Django 4.0.4 on 2022-05-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='pc_new_price',
            new_name='pt_new_price',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='pc_old_price',
            new_name='pt_old_price',
        ),
    ]
